version: '3.8'

services:
  cypress-tests:
    build: .
    container_name: cypress_tests_firefox
    volumes:
      - ./:/e2e
    command: >
      npx cypress run --browser firefox --headless --spec "cypress/e2e/tests/guiTests/*.cy.js"
