services:
  cypress-tests:
    build:
      context: .                  
      dockerfile: Dockerfile      
    container_name: cypress_tests_firefox
    volumes:
      - ./:/e2e
    working_dir: /e2e              
    command: >
      npx cypress run --browser firefox --headless --spec "cypress/e2e/tests/guiTests/*.cy.js"
