name: Cypress Tests in Docker

on:
  push:
    branches: [ hw31 ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Cypress tests
        run: |
          docker build \
            -t cypress-tests-firefox \
            --build-arg CYPRESS_BASE_IMAGE=cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1 \
            .

      - name: Run Cypress tests in Docker container
        run: |
          docker run --rm \
            --name cypress_tests_firefox \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress-tests-firefox \
            xvfb-run -a npx cypress run --browser firefox --headless --spec "cypress/e2e/tests/guiTests/*.cy.js"
