name: Cypress Tests in Docker (Debug Mode)

on:
  push:
    branches: [ hw31 ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Cypress Docker image
        run: |
          docker build -t cypress-tests-firefox .

      - name: Run Cypress tests (headless Firefox)
        run: |
          docker run --rm \
            --name cypress_tests_firefox \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress-tests-firefox \
            npx cypress run \
              --browser firefox \
              --headless \
              --spec "cypress/e2e/tests/guiTests/*.cy.js" \
              --config video=false \
              --reporter spec
