name: Cypress Tests in Docker

on:
  push:
    branches:
      - homeWork31
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cypress_tests_image .

      - name: Run Cypress tests
        run: docker run --rm cypress_tests_image
