name: Cypress Tests in Docker

on:
  push:
    branches: [ hw31 ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Cypress Docker image
        run: |
          docker build -t cypress-tests-firefox .

      - name: Run Cypress tests in Docker container
        run: |
          docker run --rm cypress-tests-firefox
